# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The lint rules applied to this project can be customized in the section below.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
